services:
  server:
    user: "1000:991"
    build:
      context: .
      dockerfile: omero-server.dockerfile
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - ./server/OMERO:/OMERO
      - ./server/data:/data
      - ./server/config:/opt/omero/server/config
      - ./server/scripts:/opt/omero/server/OMERO.server/lib/scripts/omero/scripts
      - ./server/var:/opt/omero/server/OMERO.server/var
    environment:
      - CONFIG_omero_db_host=database
      - CONFIG_omero_db_user=omero
      - CONFIG_omero_db_pass=omero
      - CONFIG_omero_db_name=omero
      - ROOTPASS=omero

  web:
    user: "999:999"
    build:
      context: .
      dockerfile: omero-web.dockerfile
    ports:
      - "4080:4080"
    volumes:
      - ./web/config:/opt/omero/web/config
      - ./web/var:/opt/omero/web/OMERO.web/var
      - ./web/templates:/opt/omero/web/OMERO.web/templates
      - ./web/static:/opt/omero/web/OMERO.web/static
      - ./web/startup/70-install-apps.sh:/startup/70-install-apps.sh
      - ./web/apps:/apps
    environment:
      - OMEROHOST=server
    develop:
      watch:
        - action: rebuild
          path: ./web/config
          target: /opt/omero/web/config
        - action: rebuild
          path: ./web/templates
          target: /opt/omero/web/OMERO.web/templates
        - action: rebuild
          path: ./web/static
          target: /opt/omero/web/OMERO.web/static
        - action: rebuild
          path: ./web/apps
          target: /apps


  database:
    image: postgres:latest
    platform: linux/amd64
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: omero
      POSTGRES_PASSWORD: omero
      POSTGRES_DB: omero
